- lib/index.js
> Fix error using incorrect method name: isAbsolutePath -> isAbsolute

- bin/serverless-artillery
- package.json
1. Because it doesn't have the .js extension, `bin/serverless-artillery` was not being linted.  Add it to the lint targets.
2. Fix linting errors
> Lint `bin/serverless-artillery` too

- lib/index.js
- package.json
- tests/serverless-artillery.spec.js
Fix #19
Include semver.
Use it to make sure the loaded version of SLS is compatible with `^1.0.3`
Update SLS mock in tests
> Check Serverless Version

- lib/lambda/handler.js
- tests/handler.spec.js
A number of parameters are used to determine when to split a script so that the entirety of the script can be executed on a single function.  This is helpful.  However, if you want to adjust them up, it is confining and requiring changing the code is largely a bit high of a bar.  Therefore, make the default values (max for single lambda) sensible (existing values) but make the hard coded maximum higher.  Do likewise for the script constraints.
Fix a few bugs:
1. Missing validation for `maxChunkRequestsPerSecond`
2. Missing validation for `timeBufferInMilliseconds`
3. an incorrect comment.
Update tests appropriately.
> Increase Hard-Coded Maximums

- lib/lambda/script.yml
This avoids the redirect from the default script.  Forgot the 's' awhile back, clearly
> Change "http" to "https"

- lib/index.js
- tests/serverless-artillery.spec.js
The -d flag seems to be interpreted by SLS as the payload and not "deployed function" anymore.
> Removed -d flag from 'invoke'

- bin/serverless-artillery
- lib/index.js
It's quite useful to be able to run tests from multiple regions using the same serverless.yml file. Serverless actually supports this via the -r cmd line parameter. I made a very small enhancement to serverless-artillery to support the same option on the command line and pass it through to serverless. Works great and allows me to launch tests from multiple regions easily.
> Add region option to deploy/remove/invoke commands

- lib/lambda/handler.js
- tests/customprocessor.js
- tests/handler.spec.js
Artillery has the concept of [processor](https://artillery.io/docs/testing_http.html#advanced-writing-custom-logic-in-javascript) for adding custom logic before/after query executions. I noticed this doesn't work in serverless-artillery. Digging a bit further it seems that artillery converts the processor value in the script into functions outside of the artillery-core project. I'm not sure why they do that, but the relevant few lines are of code can be found [here](https://github.com/shoreditch-ops/artillery/blob/master/lib/worker.js#L66). In order to get this feature to work in serverless-artillery, the equivalent procedure has to happen in the handler.js lambda. So I extended it to do just that and now I can have custom Javascript in my tests which is great!
One small issue is that the …
> Add support for artillery processor configuration

- lib/index.js
- lib/lambda/handler.js
- tests/lib/index.spec.js
- tests/lib/lambda/handler.spec.js
Fixes #83, #84, and #85.
The fix here:
https://github.com/Nordstrom/serverless-artillery/commit/7c1e56eac1de7729500f4746ed9401e775784521
missed the fact that a term confusion consistently used elsewhere was the use of settings was the driver of the issue being solved (sorry about that - maybe we should consider making length/width consistent with duration/RPS?).  Code changes elsewhere fell prey to the missed naming=>expectation causing the use of Event invocation type inappropriately.
Our injection into the call SLS path can improperly alter the SLS stack calls if it does not properly handle parse failures.  There may be more to do here to ensure that a parse failure doesn't cause acceptance of a bad result.  However, the case where this came up was when invoking the function with …
> Fix Length is Duration, Parse Failure, and Limit Check Bugs

- lib/index.js
- package-lock.json
- package.json
The refactor of variable names was not properly validated against expected behavior.  As a result, the check for whether to use the RequestResponse invocation type instead of Event type fails to notice cases where the http timeout will be hit.  As a result, in those cases, the timeout is hit and the requester goes away, failing the lambda and causing retry (i.e. the load test runs twice).
Part of why this occurred is that we don't have a set of tests for script extent.  We recently vastly increased test coverage, this was something not tested.  I want this fix published before creating those tests.  The fix has been validated by a partner that was experiencing the issue.
> Fix Duration Check Bug

- lib/index.js
- tests/lib/index.spec.js
First, the bleeding had to stop with a fix to get back to parity.
Now we need tests and perhaps a pattern that reduces ongoing bugs.  This PR provides those and fixes #91.
The logic for asking whether we need to use the event type invocation or request-response is simple.  We have an expected allowance, an expected consumption and somewhat conservative tolerances to account for a reasonable amount of unexpected.  This PR makes those assumptions more explicit and takes advantage of this to simplify the code where the results are used.
As per the prior PR, we needed tests to validate this feature.  These are added to a reasonable extent.  We can add more as we discover issues or change the implementation.  The refactor had an impact on the invoke implementation of course.
I twiddled just a …
> Fix Duration Check Bug, Continued

- README.md
- bin/serverless-artillery
- lib/index.js
- lib/lambda/funcExec.js
- lib/lambda/funcHandle.js
- lib/lambda/handler.js
- lib/lambda/taskExec.js
- package.json
- tests/lib/index.spec.js
- tests/lib/lambda/funcHandle.spec.js
- tests/lib/lambda/handler.spec.js
This PR assumes that #103 is merged prior.
Add the flags `--jo` and `--jsonOnly` to the invoke command that have the effect of suppressing all console output except for the JSON payload returned by the remote function.  This enables the piping of output to tools such as jq.
Use `log`, `warn`, and `error` as appropriate instead of just `log`
Clean up unintended logging and a commented out bit of logging that was for testing
Between these two changes, this commit fixes #100
For convenience, add a "light" script to the package.json that runs all tests excluding the long serverless-artillery.spec.js and npm.spec.js tests
> Add `--jo` & `--jsonOnly` to Invoke, Fix console.log use (fix #100)

- README.md
- lib/lambda/funcDef.js
- lib/lambda/funcValid.js
- tests/lib/lambda/funcValid.spec.js
Currently, chunks of scripts can run up to 4 minutes, but there is no hard minimum duration. These changes now require that the minimum be at least 15 seconds.
> Setting min script chunk time to 15 seconds

- lib/index.js
- lib/lambda/package-lock.json
- package-lock.json
Fixes the bug that only one monitoring mode lambda can be installed per account.  Also avoids an issue for multiple stages of the same lambda coming into conflict.
The tests affected by this change use the same constant and so did not need alteration.
> Add Service and Stage to Scheduler Name

- lib/lambda/funcExec.js
- lib/lambda/funcHandle.js
- tests/lib/lambda/funcExec.spec.js
- tests/lib/lambda/funcHandle.spec.js
This PR fixes a latent side-effect in the `execute` function in `lib/lambda/funcExec.js`. The prior logic consumed a mutable field of `lib/lambda/funcHandle.js`. The new logic eliminates the side-effect by attaching the field to the `event` parameter so that all required data is passed into the `execute` method. Tests have been updated to match.
> add function name metadata to the event

- package.json
Now the files with pattern `int.*.spec.js` will be run when you do `npm run integration`.
> WIP adding `npm run integration`

- lib/lambda/funcExec.js
- lib/lambda/funcHandle.js
- tests/lib/lambda/funcExec.spec.js
- tests/lib/lambda/funcHandle.spec.js
The functionName attribute represents private inside-baseball information.  As a result, storing it at the top level of the event seems inappropraite.  This commit and its changes propose that such settings should be stored within plugin specific hives inside of which a plugin can do whatever it likes for its own consumption.  Data stored in such a location makes no guarantees to anyone about its continued existence and should not be depended upon by any other code.
> Switch from top level to private hive

- lib/index.js
- lib/lambda/package.json
- tests/lib/func-assets-default/package.json
- tests/lib/func-assets-v0-0-1/package.json
- tests/lib/index.spec.js
Marks function assets as V0.0.1. Checks local asset version when `invoke` command is used in monitoring mode. If a legacy version is detected (no version number in `package.json`) we display the error message:
```
Your local function project assets in ${cwd()} implements a service
version that does not support invocation with the monitoring flag.
To use monitoring mode, please run the "configure" command
in a clean directory and then customize your worker's assets.
```
> Add function assets check when invoking for monitoring mode to prevent issue #161.

- lib/lambda/package-lock.json
- lib/lambda/package.json
- package-lock.json
- package.json
Correct license to remove warning during install.
Adds `audit` npm run scripts to help facilitate future audits.
**Issue #:** 
#206 BUG: number of bad packages we depend on is highly alarming
**Cause**
Packages on which we have dependencies have been updated and vulnerabilities uncovered over time.
**Description of the change**
Updates `package.json` and `package-lock.json` files to bring our dependencies up to date.
Also adds the `audit` npm run script to facilitate this task in the future. Keep in mind that `npm` 6+ will be needed.
**Open issues**
The `lib/lambda` load generator uses `artillery-core` v2. The version needed to address the vulnerabilities is two major versions greater (`artillery-core@4.8.1`). And we have yet to explore how taking this major update would affect our …
> Audit of NPM dependencies.

- README.md
Updating the version number of NodeJS to current maintenance LTS (v6+) and Serverless to v1.38+.
**Issue #:** 
#206
**Cause**
Serverless-artillery requires user to install NodeJS and Serverless before installing serverless-artillery. NodeJS v4 is now deprecated and maintenance LTS is v6 which is our new minimum requirement. With fix for issue #206 we want user to install Serverless v1.38+ in order to reduce number of dependency vulnerability.
**Description of the change**
The change updates the readme to update NodeJS and Serverless version number.
**Questions for reviewer**
None.
**Open issues**
None.
**Tests**
Verified that load testing works with the updated version of NodeJS and serverless.
> Updating the version number of NodeJS, Serverless

- README.md
- lib/index.js
- lib/lambda/serverless.yml
**Issue #:** 
https://github.com/Nordstrom/serverless-artillery/issues/236
**Cause**
AWS no longer supports the `nodejs8.10`.
**Description of the change**
Updates the `serverless.yml` to target the `nodejs10.x` Lambda runtime.
**Tests**
Tests run including ad-hoc verification that new temp directory is created if asset files differ.
> Using AWS Lambda nodejs10.x runtime.

- .gitlab-ci.yml
Due to policies attached by Nordstrom cloud team after the stack is deployed, simply deleting the stack will fail. Mitigate this by removing all policies and deleting the deployed role using the AWS CLI and JQ.
> Gitlab cicd remove policies and delete role
